In [1]:
import numpy as np
from qutip import *
from tqdm.auto import tqdm
import matplotlib.pyplot as plt
import math
from numpy import sqrt,array,isclose,linspace
import matplotlib.pyplot as plt
from numpy import *

In [2]:
from modules.spin_arch import *
from modules.su_algebra import *

In [3]:
from IPython.display import Latex

In [4]:
Ntrunc = 3 #global operator for truncation level or total number of dimensions

In [7]:
#initialize system
N = 2
Nlevel = Ntrunc

# Ej, Ec, g_arr, omega = generate_tmon_arch(N,Nlevel,o=59.87)
Ej, Ec, g_arr, omega = generate_tmon_arch(N,Nlevel)
sys1 = tmon_system(N, Nlevel, Ec, Ej, g_arr, omega)

In [28]:
sys1.freq_list()

[[0.0, 60.745553203367585, 118.99110640673517],
 [0.0, 60.745553203367585, 118.99110640673517]]

In [29]:
# a=0.40824829
# b=0.70710678
# c=0.57735027

a=1
b=sqrt(2)
c=1

In [30]:
psi_2 = a*basis(Nlevel,0) + b*sqrt(1)*basis(Nlevel,1) + c*basis(Nlevel,2)
psi_2 = psi_2/psi_2.norm()
psi_2 = psi_2 * psi_2.dag()
psi_2
rho=tensor([psi_2]*N) #sys1.tensor_projection_op(0,1,1, dim = None)

In [31]:
psi_3 = a*basis(Nlevel,0) +b*sqrt(1)*basis(Nlevel,1) + c*basis(Nlevel,2)
psi_3 = psi_3/psi_3.norm()
psi_3 = psi_3 * psi_3.dag()

rho_0=tensor([psi_3]*N)
# psi_3

In [32]:
# Spin 1
# Sx=Qobj(ensemble_op(op_padded2(Qobj(np.array([[0,sqrt(2),0],[sqrt(2),0,sqrt(2)],[0,sqrt(2),0]])/2),Nlevel), N))
# Sy=Qobj(ensemble_op(op_padded2(Qobj(1j*np.array([[0,-sqrt(2),0],[sqrt(2),0,-sqrt(2)],[0,sqrt(2),0]])/2),Nlevel), N))
# Sz=Qobj(ensemble_op(op_padded2(Qobj(np.array([[1,0,0],[0,0,0],[0,0,-1]])),Nlevel), N))

# Spin 1/2
Sx=Qobj(ensemble_op(op_padded(Qobj(np.array([[0,1,0],[1,0,1],[0,1,0]])/np.sqrt(2)),Nlevel), N))
Sy=Qobj(ensemble_op(op_padded(Qobj(1j*np.array([[0,-1,0],[1,0,-1],[0,1,0]])/np.sqrt(2)),Nlevel), N))
Sz=Qobj(ensemble_op(op_padded(Qobj(np.array([[1,0,0],[0,0,0],[0,0,-1]])),Nlevel), N))


Jsq=Sx**2+Sy**2+Sz**2
# Jsq=Qobj(array(Jsq))
Jp=Sx+1j*Sy
# Jp=Qobj(array(Jp))
Jm=Sx-1j*Sy
# Jm=Qobj(array(Jm))

In [11]:
# Phi theta calculation

nl=0

arr=[0,0,1]
# arr=[0,1,0]

def rot_basis(arr=arr):

    # Finding Eigenstates of Sz
    eigenvalues, eigenvectors = Sz.eigenstates()
    ebasis=[]
    ebasis.append(eigenvectors[-1])

    for i in (range(int(N)*(2)+1)):
        temp=Jm*ebasis[i]
        norm=sqrt((temp.dag()*temp).tr())
        if norm==0:
            print("0")
            break
        ebasis.append(temp/norm)

    # Finding angle to rotate into
    n1=sqrt(arr[0]**2+arr[1]**2)
    if n1==0:
        phi=0
    else:
        phi=arccos(arr[0]/n1)+pi/2
    theta=pi/2-arccos(n1)

    # Rotating in the required basis
    tlist=linspace(0,theta+0.0001,100)
    H=cos(phi)*Sx+sin(phi)*Sy
    n=0
    for i in (ebasis):
    #     options=Options()
    #     options.
        res1=mcsolve(H,i,tlist,[],[],ntraj=1, progress_bar=None)
        ebasis[n]=res1.states[-1]
        n+=1

    return ebasis

In [12]:
array_rot_basis=array([0,1,0])
nly=rot_basis(array_rot_basis/linalg.norm(array_rot_basis))
nlz=rot_basis([0,0,1])

0
No c_ops, using sesolve
No c_ops, using sesolve
No c_ops, using sesolve
No c_ops, using sesolve
No c_ops, using sesolve
No c_ops, using sesolve
No c_ops, using sesolve
No c_ops, using sesolve
No c_ops, using sesolve
No c_ops, using sesolve
No c_ops, using sesolve
0
No c_ops, using sesolve
No c_ops, using sesolve
No c_ops, using sesolve
No c_ops, using sesolve
No c_ops, using sesolve
No c_ops, using sesolve
No c_ops, using sesolve
No c_ops, using sesolve
No c_ops, using sesolve
No c_ops, using sesolve
No c_ops, using sesolve


In [8]:
H = sys1.H_I()
H_ph= -Sx



55 0.0 1.0
55 60.745553203367585 1.0
55 0.0 1.0
55 60.745553203367585 1.0


NameError: name 'Sx' is not defined

In [9]:
H

Quantum object: dims = [[3, 3], [3, 3]], shape = (9, 9), type = oper, isherm = True
Qobj data =
[[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.01818182  0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.01818182  0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.         -0.34809529  0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.         -0.34809529
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.   

In [35]:
−0.348

0.01818181818181818

In [36]:
2/5

0.4

In [34]:
H

Quantum object: dims = [[3, 3], [3, 3]], shape = (9, 9), type = oper, isherm = True
Qobj data =
[[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.01670286  0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.01670286  0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.         -2.2842701   0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.         -2.2842701
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.    

In [14]:
sys1.tensor_projection_op(0,0,1)[15]

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 

In [22]:
H

Quantum object: dims = [[3, 3, 3, 3, 3], [3, 3, 3, 3, 3]], shape = (243, 243), type = oper, isherm = True
Qobj data =
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [16]:
# Function for Eigenspectrum
def eigenspectrum(rho,nl=0):
    if nl==0:
        nl=rot_basis()
    prob=[]
    for i in nl:
        prob.append(expect(rho,i*i.dag()))
    return array(prob)

In [17]:
def hell_dist(rho,rho_0,nl):
    return 1-sum(sqrt(eigenspectrum(rho,nl)*eigenspectrum(rho_0,nl)))

In [18]:
# t1=5.2525,t2=15.5555
def time_evol(rho,t_ph=0,t1=175,t2=86.285,H_ph=H_ph,H=H):
    # First part: entanglement generation
    times = np.linspace(0,t1,100) 
    options = Options()
    options.store_final_state = True
    rho = mesolve(H, rho, times, [], options = options, progress_bar=True).states[-1]

    # Second part: phase encoding

#     times = np.linspace(0,t_ph,int(t_ph+10)) #time scale is ~ 1/freq of self energy 
#     options = Options()
#     options.store_final_state = True
#     rho = mesolve(H_ph, rho, times, [], options = options, progress_bar=True).states[-1]

#     # Third part: entanglement decoding
#     times = np.linspace(0,t2,100) #time scale is ~ 1/freq of self energy 
#     options = Options()
#     options.store_final_state = True
#     rho = mesolve(-H, rho, times, [], options = options, progress_bar=True).states[-1]

    return rho

In [19]:
t_ph=0.1
a=time_evol(rho)

10.0%. Run time:  15.71s. Est. time left: 00:00:02:21


KeyboardInterrupt: 

In [ ]:
sum(eigenspectrum(a,nly))

In [ ]:
ang=linspace(-N,N,int(2*(N)+1))
# plt.plot(ang,(eigenspectrum(time_evol(rho,t_ph),nly)),".")
plt.plot(ang,(eigenspectrum(a,nly)),".")
plt.grid()
plt.plot(ang,(eigenspectrum(rho,nly)),".")
plt.title("Distribution in Sz basis")

In [ ]:
# a=time_evol(rho,t_ph)
hell_dist(a,rho,nly),hell_dist(a,rho,nlz)

In [ ]:
t_ph=0.002

In [ ]:
arr1=[0.76894092,0.62212189,0.14728953]
arr2=[0,1,0]
nl=[rot_basis(arr1),rot_basis(arr2)]
hdist=[]
rho1=time_evol(rho,t_ph)
for i in nl:
    hdist.append(hell_dist(rho1,rho_0,i))
print(hdist)

In [ ]:
t_ph=linspace(0.00000001,0.02,10)
arr1=[0,1,0]
arr2=array([0,9.32410521e-01,2.69307118e-01])/0.9705234172738736
nl=[rot_basis(arr1),rot_basis(arr2)]
hdist=[]

for i in tqdm(t_ph):
    rho1=time_evol(rho,i)
    temp=[]
    for i in nl:
        temp.append(hell_dist(rho1,rho_0,i))
    hdist.append(temp)
hdist=array(hdist)

In [ ]:
plt.plot(t_ph,hdist.transpose()[0])
plt.plot(t_ph,hdist.transpose()[1])
plt.xlim([0,0.0025])
plt.ylim([0,0.00009])

In [ ]:
ang=linspace(-N/2,N/2,int(2*(N/2)+1))
plt.plot(array(ang),(eigenspectrum(time_evol(rho,0.0001),nl[0])),'.')
plt.plot(array(ang),(eigenspectrum(rho_0,nl[0])),'.')

In [ ]:
arr2=[[0],[9.32410521e-01],[2.69307118e-01]]
Qobj(arr2).norm()